Blog page
women-on-rails/ressources pull request #40
Opened 2020-10-22 09:09 UTC by morganbonhomme

## Pourquoi cette Pull Request ?
#23 Faire un index pour les articles du blog

## Qu'est-ce qui a été changé ?

- Ajout d'un nouveau component `blog_card.js` dans `website/src/components/`. Ce component est une card [Infima](https://facebookincubator.github.io/infima/docs/components/card). Customisation pour que ca passe bien en dark mode. 
- Création d'une page custom en React dans `blog-index.js `dans `website/src/pages/blog-index.js`.
- Changement de la navbar et donc mise à jour du `docusaurus.config.js` pour enlever le lien vers le blog et créer un lien vers la nouvelle page d'index du blog. 

## Screenshots

Avant : 
![Capture d’écran 2020-10-22 à 11 06 08](https://user-images.githubusercontent.com/62025173/96850048-a8ffa000-1456-11eb-9c7b-40f70a5cf3bb.png)

Après: 
![Capture d’écran 2020-10-22 à 11 06 21](https://user-images.githubusercontent.com/62025173/96850065-adc45400-1456-11eb-8809-f41ff02c4754.png)

2020-10-22 12:49 UTC, AJuliette commented
Top ! Je relis ça ce soir, attention il y a un conflit

2020-10-23 07:38 UTC, AJuliette reviewed
Des retours plus globaux:
- top d'avoir défini les classes `card__link`, `card__date`, `card__tag`, `card__author` en respectant la convention
- top d'avoir fait le hover global sur la carte
- top d'avoir pensé au Dark mode 

Vu que là il y a beaucoup de css pour la card, je pense qu'il faut le mettre dans un fichier à part que tu importes dans le fichier `custom.css`
Pour la gestion du dark theme, j'ai l'impression qu'il y a une façon "plus propre" où tu définis des variables directement dans le css et elles se changent selon le mode, plutôt que de gérer ça côté JS. C'est ma faute, j'ai pas du tout eu le temps de m'y pencher et de préparer une doc (j'ai pas été confronté à ça jusqu'à présent ^^"). Donc je vais regarder et je te dis

2020-10-23 07:38 UTC, AJuliette commented on website/docusaurus.config.js
> +          to: 'blog-index',
J'ai testé en local, si on fait comme ça, la route `blog` reste avec l'ancien design, mais si tu renommes le fichier et la route `blog` ça override l'ancienne page

2020-10-23 07:38 UTC, AJuliette commented on website/src/css/custom.css
> +  box-sizing: border-box;
Très bon réflexe le `box-sizing: border-box;` ! J'ai vérifié par contre, c'est déjà mis dans le css de Docusaurus

2020-10-23 07:38 UTC, AJuliette commented on website/src/css/custom.css
> +}
J'ai l'impression que le `box-sizing: inherit;` est du coup remis en cause par l'autre box-sizing que tu mets en-dessous non ?
Pour le margin et padding à 0 partout, c'est une décision un peu "forte", je pense qu'il vaut mieux le faire élément par élément dont tu souhaites réviser le padding et le margin parce que là sinon ça change tout le site

2020-10-23 07:38 UTC, AJuliette commented on website/src/components/blog_card.js
> +
Attention aux espaces en trop

2020-10-23 07:38 UTC, AJuliette commented on website/src/css/custom.css
> +
Espace en trop :p

2020-10-23 07:38 UTC, AJuliette commented on website/src/css/custom.css
> +
Espace en trop :p

2020-10-23 07:38 UTC, AJuliette commented on website/src/css/custom.css
> +
Espace en trop :p

2020-10-23 07:40 UTC, AJuliette requested changes

2020-10-23 07:40 UTC, AJuliette commented on website/src/css/custom.css
> +}
Finalement tu ne t'es pas servi de cette classe

2020-10-23 07:40 UTC, AJuliette commented on website/src/css/custom.css
> +}
Dans ton component je vois un `card_header` mais pas de `header` ?

2020-10-23 07:47 UTC, AJuliette commented on website/src/css/custom.css
> +  box-sizing: border-box;
Je connaissais pas `font-size: 100%;`, merci !

2020-10-23 10:05 UTC, clodiap commented on website/src/css/custom.css
> +}
Hello :cat: 
Le margin et padding à 0, ça fait partie de ce qu'on appelle "reset css", chaque navigateur ayant ses propres valeurs de base de margin et padding pour chaque élément, en mettant ces valeurs à 0 on s'assure que tous les éléments s'afficheront pareil dans chaque navigateur (enfin en théorie ^^). Après il y a peut-être un reset dans Infima, je vais regarder.

2020-10-23 10:09 UTC, clodiap commented
> => Pour la gestion du dark theme, j'ai l'impression qu'il y a une façon "plus propre" où tu définis des variables directement dans le css et elles se changent selon le mode, plutôt que de gérer ça côté JS. C'est ma faute, j'ai pas du tout eu le temps de m'y pencher et de préparer une doc (j'ai pas été confronté à ça jusqu'à présent ^^"). Donc je vais regarder et je te dis comment faire ça

Tiens ce matin je suis tombée sur ce lien : [ Dark mode easily on the web ](https://dev.to/medhatdawoud/dark-mode-easily-on-the-web-5h6a)

2020-10-23 10:15 UTC, clodiap commented on website/src/css/custom.css
> +}
Hop voici le fichier `base.css` de Infima, avec un reset de margin mais pas de padding : 
```css
* {
  box-sizing: border-box;
}

html {
  background-color: var(--ifm-background-color);
  box-sizing: border-box;
  color: var(--ifm-font-color-base);
  line-height: var(--ifm-line-height-base);
  font-family: var(--ifm-font-family-base);
  font-size: var(--ifm-font-size-base);
  text-rendering: optimizelegibility;

  -webkit-tap-highlight-color: transparent;
  -webkit-font-smoothing: antialiased;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}

body {
  margin: 0;
  word-wrap: break-word;
}
```
Un article intéressant sur les reset : https://css-tricks.com/reboot-resets-reasoning/

2020-10-23 11:16 UTC, AJuliette commented on website/src/css/custom.css
> +}
Ok du coup j'ai rien dit pour le padding et le margin, merci Clodia !

2020-10-23 12:05 UTC, morganbonhomme commented on website/src/components/blog_card.js
> +
Effectivement je vais corriger ça partout, sorry :)

2020-10-23 12:23 UTC, morganbonhomme commented on website/docusaurus.config.js
> +          to: 'blog-index',
Je suis pas sûre d'avoir compris, tu parles de renommer le fichier blog ou le fichier blog-index ? Histoire que je ne fasse pas de bêtises :) Merci !

2020-10-23 15:27 UTC, AJuliette commented on website/docusaurus.config.js
> +          to: 'blog-index',
Ah désolée ! Il faut renommer `blog-index.js` en `blog` et du coup corriger là

2020-10-25 19:21 UTC, AJuliette commented
Hello @morganbonhomme  !
Pour reprendre au niveau de l'organisation des fichiers:
- [ ] les fichiers `css` restent ensemble donc il faut que dans `src/css` tu aies le `custom.css` et `blog_card.css`. Tu peux importer le css du blog dans le fichier `custom.css` en mettant au début: `@import "blog_card.css";`
- [ ] du coup pas besoin de mettre le `blog_card.js` dans un sous-dossier + tu peux importer le fichier `blog_card.js` dans `blog.js` en faisant: `import BlogCard from "@site/src/components/blog_card.js";`
- [ ] pour le fichier `blog-index.js`, il faut le renommer `blog.js` et donc changer la route dans le fichier `docusaurus.config.js` de `blog-index` à `blog`

2020-10-25 19:46 UTC, AJuliette requested changes
Hello @morganbonhomme  !
Pour reprendre au niveau de l'organisation des fichiers:
- [ ] les fichiers `css` restent ensemble donc il faut que dans `src/css` tu aies le `custom.css` et `blog_card.css`. Tu peux importer le css du blog dans le fichier `custom.css` en mettant au début: `@import "blog_card.css";`
- [ ] du coup pas besoin de mettre le `blog_card.js` dans un sous-dossier + tu peux importer le fichier `blog_card.js` dans `blog.js` en faisant: `import BlogCard from "@site/src/components/blog_card.js";`
- [ ] pour le fichier `blog-index.js`, il faut le renommer `blog.js` et donc changer la route dans le fichier `docusaurus.config.js` de `blog-index` à `blog`

Au niveau des couleurs, j'ai enfin compris le système, c'est un peu comme ce que tu avais trouvé @clodiap (mais automatisé avec le système Docusaurus). 
Tu dois définir tes couleurs dans des variables, par exemple pour le css `.card:hover`:

```css
.card:hover {
  box-shadow: 0 0.5rem 1rem var(--ifm-color-card-hover);
  transform: translateY(-3px);
}
```

Dans le fichier `custom.css`, tu rajoutes ta couleur dans `root`:

```css
:root {
  --ifm-color-primary: #1B998B;
  --ifm-color-primary-dark: #188a7d;
  --ifm-color-primary-darker: #178276;
  --ifm-color-primary-darkest: #136b61;
  --ifm-color-primary-light: #1ea899;
  --ifm-color-primary-lighter: #1fb0a0;
  --ifm-color-primary-lightest: #23c7b5;
  --ifm-color-card-hover: rgba(0, 0, 0, 0.2);
}
```

Si tu veux définir une couleur pour le dark pour cette variable tu n'as plus qu'à faire:
```css
html[data-theme='dark'] {
  --ifm-color-card-hover: var(--ifm-color-white);
}
```
=> c'est à dire: `--la-variable: var(--la-variable-que-tu-veux-pour-le-dark`

Voici les couleurs dont le côté dark est déjà défini:
```css
html[data-theme='dark'] {
  --ifm-color-emphasis-0: var(--ifm-color-gray-1000);
  --ifm-color-emphasis-100: var(--ifm-color-gray-900);
  --ifm-color-emphasis-200: var(--ifm-color-gray-800);
  --ifm-color-emphasis-300: var(--ifm-color-gray-700);
  --ifm-color-emphasis-400: var(--ifm-color-gray-600);
  --ifm-color-emphasis-500: var(--ifm-color-gray-500);
  --ifm-color-emphasis-600: var(--ifm-color-gray-400);
  --ifm-color-emphasis-700: var(--ifm-color-gray-300);
  --ifm-color-emphasis-800: var(--ifm-color-gray-200);
  --ifm-color-emphasis-900: var(--ifm-color-gray-100);
  --ifm-color-emphasis-1000: var(--ifm-color-gray-0);

  --ifm-background-color: #18191a;
  --ifm-background-surface-color: #242526;

  --ifm-hover-overlay: rgba(255, 255, 255, 0.05);

  --ifm-menu-link-sublist-icon: url('data:image/svg+xml;utf8,<svg alt="Arrow" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24"><path fill="rgba(255,255,255,0.6)" d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6z"></path></svg>');

  --ifm-color-content-secondary: rgba(255, 255, 255, 1);
}
```

Qui correspondent à ces couleurs:
<img width="424" alt="Capture d’écran 2020-10-25 à 20 43 48" src="https://user-images.githubusercontent.com/42354334/97117266-d1abc200-1702-11eb-9db7-ca9af648620e.png">

=> Donc ça veut dire que si par exemple tu veux te servir de la variable `--ifm-color-emphasis-100` tu n'as pas à t'inquiéter de son rendu en dark car il est déjà défini.

Voilà désolée, c'était long, j'espère que c'est clair ! Si tu veux on peut faire une session de code ensemble pour revoir ça :)

2020-10-25 19:46 UTC, AJuliette commented on website/src/components/blog_card/blog_card.js
> +    <div className={`card--demo${style}`}>
Tu peux supprimer cette div qui encadre ta card, elle ne te sert à rien

2020-10-27 09:59 UTC, morganbonhomme commented
@AJuliette Merci pour les infos ! J'ai cleané le code du coup :)

2020-10-27 17:41 UTC, AJuliette requested changes
Au top, merci et bravo ! Juste les deux petites lignes inutiles à changer
Je ne sais pas si tu le fais déjà mais moi ça m'aide beaucoup après avoir pusher mes changements de relire le code dans la partie `Files changed`, c'est souvent là que je vois et corrige toutes les petites erreurs que j'ai laissé passer.

2020-10-27 17:41 UTC, AJuliette commented on website/src/components/blog_card.js
> +  const { isDarkTheme, setLightTheme, setDarkTheme } = useThemeContext();
👀🐯 Tu peux enlever ces deux lignes du coup:
`import useThemeContext from "@theme/hooks/useThemeContext";`
et `const { isDarkTheme, setLightTheme, setDarkTheme } = useThemeContext();`

2020-10-27 18:28 UTC, morganbonhomme commented on website/src/components/blog_card.js
> +  const { isDarkTheme, setLightTheme, setDarkTheme } = useThemeContext();
Merci à toi pour la relecture !  
C'est la première fois que je contribue à un projet open source et c'est cool ! 
J'ai changé, normalement c'est ok :)

2020-10-27 19:20 UTC, AJuliette commented on website/src/components/blog_card.js
> +  const { isDarkTheme, setLightTheme, setDarkTheme } = useThemeContext();
Super merci :) C'est la première fois pour moi que je fais ça et que je fais des retours sur des PR donc pour moi aussi c'est un apprentissage; mais en tous cas merci d'être au taquet comme ça, ça fait plaisir !

2020-10-27 19:20 UTC, AJuliette approved these changes

2020-10-27 19:20 UTC, merged

2020-10-27 19:23 UTC, AJuliette commented
Bravo ! 

![Alt Text](https://media.tenor.com/images/05c077c063e84bda32dafbb1d505a41b/tenor.gif)

2020-10-27 19:27 UTC, AJuliette commented
C'est en ligne :3 
https://women-on-rails.github.io/ressources/blog/