Add different resources in a bunch of pages plus update design when i am at it
women-on-rails/ressources pull request #51
Opened 2020-11-11 17:20 UTC by AJuliette

## Pourquoi cette Pull Request ?

À la base je voulais ajouter quelques liens ressources et puis ça a basculé...

## Qu'est-ce qui a été changé ?

- J'ai sorti la page `Faire son profil en ligne` de la catégorie `Trouver un job` et j'ai fait une catégorie à part avec dedans comme pages: `CV`, `Portfolio`, `Blog`

<b>La page CV:</b>

<img width="426" alt="Capture d’écran 2020-11-11 à 18 17 34" src="https://user-images.githubusercontent.com/42354334/98842660-2f9e1080-244a-11eb-8a56-9ac3e21fe977.png">

<b>La page portfolio:</b>

<img width="562" alt="Capture d’écran 2020-11-11 à 18 18 13" src="https://user-images.githubusercontent.com/42354334/98842739-4d6b7580-244a-11eb-8281-9db59cf3eff9.png">

<b>La page blog:</b>

<img width="420" alt="Capture d’écran 2020-11-11 à 18 18 48" src="https://user-images.githubusercontent.com/42354334/98842803-5f4d1880-244a-11eb-89c0-630c82ef16d5.png">

- J'ai rajouté une section `checklist pour faire la différence` dans la page tests techniques
<img width="830" alt="Capture d’écran 2020-11-11 à 18 14 42" src="https://user-images.githubusercontent.com/42354334/98842382-c8805c00-2449-11eb-97cd-0754bd16a65b.png">

- J'ai rajouté un site sur la page s'entraîner aux tests

- J'ai amélioré le design de la page `Les offres`
<img width="567" alt="Capture d’écran 2020-11-11 à 18 16 36" src="https://user-images.githubusercontent.com/42354334/98842563-0c736100-244a-11eb-8fea-b036cb4d66ae.png">

2020-11-12 11:30 UTC, clodiap reviewed
J'ai vu quelques petites fautes, à part ça c'est chouette, bravo :+1: 
Sympa les génerateurs de profile readme sur Github, et aussi les générateurs de sites statiques :heart_eyes_cat: 
Ah et hashnode ça a l'air sympa aussi, je connaissais pas.

2020-11-12 11:30 UTC, clodiap commented on website/docs/find_a_job/interview-types.md
> +| ✅ | Organiser son code: essayer de donner des noms signifiants aux variables, extraire dans des méthodes quand c’est pertinent, ou dans des classes. |
```suggestion
| ✅ | Organiser son code: essayer de donner des noms de variables significatifs, extraire dans des méthodes quand c’est pertinent, ou dans des classes. |
```
Signifiant ou significatif ?

2020-11-12 11:30 UTC, clodiap commented on website/docs/online_profile/blog.mdx
> +Un autre moyen de partager ce que tu écrits ce sont des plateformes qui mixent blog et newsletter: chaque article est directement envoyé à tes abonné·e·s. Les articles sont conservés à un même endroi
```suggestion
Un autre moyen de partager ce que tu écris ce sont des plateformes qui mixent blog et newsletter : chaque article est directement envoyé à tes abonné·e·s. Les articles sont conservés à un même endroit donc consultables en ligne.<br/>
```

2020-11-12 11:30 UTC, clodiap commented on website/docs/online_profile/portfolio.mdx
> +On liste en-dessous des générateurs de sites statiques en Ruby, mais bien sûr il y en a dans d'autres langages. Tu peux trouver une [liste exhausite de générateurs de sites statiques ici](https://jam
```suggestion
On liste en-dessous des générateurs de sites statiques en Ruby, mais bien sûr il y en a dans d'autres langages. Tu peux trouver une [liste exhaustive de générateurs de sites statiques ici](https://jamstack.org/generators/).
```

2020-11-12 11:30 UTC, clodiap commented on website/docs/online_profile/portfolio.mdx
> +    description="Troisième place sur le podium, les pages de Middleman sont aux formats erb et haml."
C'est la même description que pour Middleman ^^

2020-11-12 12:33 UTC, AJuliette commented on website/docs/online_profile/portfolio.mdx
> +    description="Troisième place sur le podium, les pages de Middleman sont aux formats erb et haml."
Oui parce qu'il y a pas vraiment de différence 😆  Enfin j'ai pas vu plus, je vais voir

2020-11-12 16:11 UTC, clodiap commented on website/docs/online_profile/portfolio.mdx
> +    description="Troisième place sur le podium, les pages de Middleman sont aux formats erb et haml."
Ah :smile: , du coup faudrait juste mettre "…les pages de Nanoc…"
```suggestion
    description="Troisième place sur le podium, les pages de Nanoc sont aux formats erb et haml."
```

2020-11-12 18:40 UTC, AJuliette commented on website/docs/online_profile/portfolio.mdx
> +    description="Troisième place sur le podium, les pages de Middleman sont aux formats erb et haml."
Ok j'ai changé en local !

2020-11-12 18:40 UTC, AJuliette commented on website/docs/online_profile/blog.mdx
> +Un autre moyen de partager ce que tu écrits ce sont des plateformes qui mixent blog et newsletter: chaque article est directement envoyé à tes abonné·e·s. Les articles sont conservés à un même endroi
Changé en local, merci !

2020-11-12 18:41 UTC, AJuliette commented
Merci ! 🙏  J'ai corrigé les typos et sur la page portfolio j'ai ajouté une catégorie CMS. Contente que tu aies appris des trucs ! :3 
Je vais "juste" rajouter le SEO sur les pages

2020-11-13 07:30 UTC, AJuliette commented
Bon le SEO ça prend du temps ahah et en plus je réarrange les pages en le faisant (je modifie le titre et les sous-titres pour le référencement), je vais poster peu à peu les pages :3 
![Localhost - Full - iPad - 2020-11-13 at 8 30 07 AM](https://user-images.githubusercontent.com/42354334/99041042-7abf3d00-258a-11eb-950e-abe452eeda01.jpg)

2020-11-13 17:53 UTC, clodiap commented
Je viens de tomber sur BridgeTown, un générateur de site statique : https://www.bridgetownrb.com/ 
« A Webpack-aware, Ruby-powered static site generator for the modern Jamstack era.» ça a l'air sympa ^^

2020-11-14 15:00 UTC, AJuliette commented
> Je viens de tomber sur BridgeTown, un générateur de site statique : https://www.bridgetownrb.com/
> « A Webpack-aware, Ruby-powered static site generator for the modern Jamstack era.» ça a l'air sympa ^^

Héhé, dans la newsletter de Ruby Weekly ? 
J'ai fait un tour des autres "petits" générateurs statiques en ruby et `Bridgetown` et le seul a avoir été mis à jour récemment, bien vu, je le rajoute !

2020-11-14 18:23 UTC, AJuliette commented
La nouvelle page portfolio:
![Localhost - Full - iPad - 2020-11-14 at 7 23 11 PM](https://user-images.githubusercontent.com/42354334/99154278-df73b800-26ae-11eb-9c7c-88633e8451e8.jpg)

2020-11-15 09:42 UTC, clodiap commented
> Héhé, dans la newsletter de Ruby Weekly ?

Je l'ai d'abord vu passer sur Twitter :bird: , puis après dans la newsletter de Ruby Weekly ^^

2020-11-15 10:18 UTC, clodiap submitted a review, later dismissed
:+1: Bravo !

2020-11-15 11:24 UTC, AJuliette commented
Merci ! Le mieux est l'ennemi du bien, mais j'ai juste encore deux petits trucs à ajouter sur la page portfolio et j'y touche plus, P-R-O-M-I-S

2020-11-15 14:40 UTC, AJuliette commented
Comme disait si bien Britney, [oops, I did it again](https://www.youtube.com/watch?v=CduA0TULnow), mais ça y est je suis satisfaite, j'ai ajouté les headless CMS sur la page portfolio (ça me turlupinait) + j'ai fait une page avec des ressources pour le design

2020-11-15 14:44 UTC, AJuliette commented
La partie sur headless cms sur la page portfolio: 

<img width="636" alt="Capture d’écran 2020-11-15 à 15 43 02" src="https://user-images.githubusercontent.com/42354334/99187852-42218e00-2759-11eb-9fee-9c543284b094.png">
<img width="624" alt="Capture d’écran 2020-11-15 à 15 43 15" src="https://user-images.githubusercontent.com/42354334/99187857-48176f00-2759-11eb-970b-5107df5760d6.png">

2020-11-15 14:47 UTC, AJuliette commented
La nouvelle page avec des ressources design: 
![FireShot Capture 013 - Des ressources gratuites pour le design - Women On Rails - localhost](https://user-images.githubusercontent.com/42354334/99187933-c83dd480-2759-11eb-859b-1a8daa73ce1c.png)

2020-11-17 18:45 UTC, clodiap requested changes
Sympa les ressources gratuites :+1: et l'article sur les headless CMS  :+1: :cat:

2020-11-17 18:45 UTC, clodiap commented on website/docs/online_profile/portfolio.mdx
> +C'est un moyen de regrouper au même endroit ce que tu produits en ligne: tes articles, tes projets web... Ça peut être aussi un challenge front en le codant.<br/>
```suggestion
C'est un moyen de regrouper au même endroit ce que tu produis en ligne: tes articles, tes projets web... Ça peut être aussi un challenge front en le codant.<br/>
```

2020-11-17 18:45 UTC, clodiap commented on website/docs/online_profile/portfolio.mdx
> +Les **headless CMS** sont des services qui te permettent d'ajouter une interface web afin de gérer les contenus de ton site.
Je propose une petit modif pour clarifier un peu :cat: 
```suggestion
Les **headless CMS** sont des services qui te permettent d'ajouter une interface web d'administration afin de gérer les contenus de ton site.
```

2020-11-17 19:20 UTC, AJuliette commented on website/docs/online_profile/portfolio.mdx
> +C'est un moyen de regrouper au même endroit ce que tu produits en ligne: tes articles, tes projets web... Ça peut être aussi un challenge front en le codant.<br/>
Ouh là j'ai vraiment un problème avec les verbes du troisième groupe 😆

2020-11-17 19:22 UTC, AJuliette commented
Merci de ta relecture <3

2020-11-18 10:58 UTC, clodiap approved these changes
:+1:

2020-11-18 11:37 UTC, merged