Documentation sur les components
women-on-rails/ressources pull request #52
Opened 2020-11-12 17:35 UTC by clodiap

## Pourquoi cette Pull Request ?

Issue #29 : Créer une page recensant tous les components

## Qu'est-ce qui a été changé ?

* J'ai créé une page recensant les components utilisés dans l'application et expliquant leur fonctionnement.
* J'ai supprimé la partie sur les components dans le fichier `CONTRIBUTING.md` et je l'ai remplacée par un lien vers la page `components.md`

2020-11-13 07:24 UTC, AJuliette commented
Top merci ! 🥳  Je review ça ce week-end !

2020-11-14 19:06 UTC, AJuliette commented
Juste pour info, comme tu as les droits d'écriture, tu peux clone le repo principal et faire tes branches au lieu de passer par ton fork

2020-11-14 19:26 UTC, AJuliette commented
Merci pour ce gros travail 🙏

2020-11-14 21:25 UTC, AJuliette requested changes

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +Docusaurus (le framework faisant tourner ce site) est réalisé en React et de ce fait nous pouvons utiliser des composants dans les fichiers ressources `.mdx` et bien sûr `js`.
```suggestion
Docusaurus (le framework faisant tourner ce site) est réalisé en React et de ce fait nous pouvons utiliser des composants dans les fichiers ressources `.mdx` et bien sûr `.js`.
```

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +Pour en savoir plus sur le format `.mdx`, tu peux te référer à la [doc](https://v2.docusaurus.io/docs/markdown-features/#embedding-react-components-with-mdx).
```suggestion
```

(La phrase est déjà présente ligne 14)

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +### CSS modules
Top d'avoir rajouté une présentation des modules ! 👌

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +## Les components de base de Docusaurus
Top d'y avoir pensé 👍

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +  Tu peux t'inspirer de components présents déjà assez simples comme celui pour les [avatars](https://github.com/women-on-rails/ressources/blob/master/website/src/components/avatar.js).</br>
```suggestion
  Si tu créées un élément que tu penses seras utile à d'autres endroits du site, tu peux en faire un component qui sera utilisable par d'autres !<br/>
  Tu peux t'inspirer de components présents déjà assez simples comme celui pour les [avatars](https://github.com/women-on-rails/ressources/blob/master/website/src/components/avatar.js) vu plus haut.</br>
```
Comme le lien présentant le JSX a été déjà mis plus haut :3

2020-11-14 21:25 UTC, AJuliette commented on components.md
> +:bulb: Petit tip: n'oublie pas `import React from 'react';` au début du fichier.
```suggestion
:bulb: Petit tip: n'oublie pas `import React from 'react';` au début du fichier de ton component.
```

Je me rends compte que cette phrase était pas assez précise sur où mettre la ligne ^^"

2020-11-15 09:48 UTC, clodiap commented
> Juste pour info, comme tu as les droits d'écriture, tu peux clone le repo principal et faire tes branches au lieu de passer par ton fork
Oui c'est vrai, c'est l'habitude ^^

> +Je ne sais pas quel éditeur de code tu utilises, mais tu peux installer un plugin qui permet d'avoir un preview des pages Markdown. Sur VSCode j'ai installé `Markdown All in One` pour ça

J'utilise Vim, c'est vrai que ce serait plus pratique d'avoir une preview, je vais regarder ça :cat:

2020-11-15 10:29 UTC, AJuliette approved these changes

2020-11-15 10:29 UTC, merged