Add company interviewing page
women-on-rails/ressources pull request #65
Opened 2021-04-19 21:20 UTC by AJuliette

## Pourquoi cette Pull Request ?
Ajout d'une page sur comment se faire son avis sur une entreprise pour laquelle on candidate.

## Screenshots
<img width="578" alt="Capture d’écran 2021-04-19 à 23 20 34" src="https://user-images.githubusercontent.com/42354334/115304936-d9a26700-a165-11eb-84f5-a93a54b6cee6.png">

2021-04-20 18:38 UTC, clodiap requested changes
J'ai trouvé quelques petites fautes :wink:

2021-04-20 18:38 UTC, clodiap commented on website/docs/find_a_job/company-interviewing.mdx
> +  description="Compte Instagram qui publie anonyment des avis (positifs ou négatifs) d'employé·e·s, passé·e·s ou présent·e·s"
```suggestion
  description="Compte Instagram qui publie anonymement des avis (positifs ou négatifs) d'employé·e·s, passé·e·s ou présent·e·s"
```

2021-04-20 18:38 UTC, clodiap commented on website/docs/find_a_job/company-interviewing.mdx
> +Même si ça peut faire peur, on peut poser des questions quand on passe des entretiens pour déterminer si on pourra si sentir bien ou pas.
```suggestion
Même si ça peut faire peur, on peut poser des questions quand on passe des entretiens pour déterminer si on pourra s'y sentir bien ou pas. 
```

2021-04-20 18:38 UTC, clodiap commented on website/docs/find_a_job/company-interviewing.mdx
> +On peut aussi consulter des réseaux où d'anciennes ou d'ancien·ne·s salarié·e·s laissent un avis sur leur expérience au sein de l'entreprise:
```suggestion
On peut aussi consulter des réseaux où d'ancien·ne·s salarié·e·s laissent un avis sur leur expérience au sein de l'entreprise:
```

2021-04-21 15:18 UTC, AJuliette commented
J'écris de plus en plus selon les sons, c'est catastrophique ahah

2021-04-23 10:57 UTC, clodiap approved these changes
:+1:

2021-06-13 19:01 UTC, merged